# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_fave',
            field=models.BooleanField(default=False),
        ),
    ]
